const axios = require('axios');
const StudentActivity = require('../models/StudentActivity');

const insightSchema = {
  type: 'OBJECT',
  properties: {
    summary: { type: 'STRING' },
    strengths: { type: 'ARRAY', items: { type: 'STRING' } },
    suggestedActions: { type: 'ARRAY', items: { type: 'STRING' } },
    discussionQuestions: { type: 'ARRAY', items: { type: 'STRING' } },
    disclaimer: { type: 'STRING' },
  },
  required: ['summary', 'strengths', 'suggestedActions', 'discussionQuestions', 'disclaimer'],
};

const promptFor = ({ record, forecast }) => `You are a student-support assistant. Explain the supplied forecast in calm, practical, non-judgmental language.

Rules:
- Do not diagnose, label, shame, or make admissions, disciplinary, financial-aid, or academic decisions.
- Do not claim certainty or infer facts not in the data.
- Suggest no more than three concrete, student-controlled actions.
- Encourage discussion with an adviser or professor where helpful.
- Make clear that the forecast is not a decision or diagnosis.

Academic context (provided by the student): ${JSON.stringify(record)}
Forecast (generated by the academic model): ${JSON.stringify(forecast)}`;

exports.generateMySupportInsight = async (req, res, next) => {
  try {
    if (req.user.role !== 'student') return res.status(403).json({ message: 'Only students can generate support insights.' });
    if (!process.env.GEMINI_API_KEY) return res.status(503).json({ message: 'Student support insights are not configured yet. Add GEMINI_API_KEY to the backend environment.' });

    const latestForecast = await StudentActivity.findOne({ student: req.user._id, type: 'forecast_run' }).sort({ createdAt: -1 }).lean();
    if (!latestForecast) return res.status(400).json({ message: 'Run a forecast before requesting support suggestions.' });

    const model = process.env.GEMINI_MODEL || 'gemini-2.5-flash-lite';
    const { data } = await axios.post(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`, {
      contents: [{ parts: [{ text: promptFor(latestForecast) }] }],
      generationConfig: { responseMimeType: 'application/json', responseSchema: insightSchema, temperature: 0.2 },
    }, {
      headers: { 'x-goog-api-key': process.env.GEMINI_API_KEY, 'Content-Type': 'application/json' },
      timeout: 20000,
    });
    const text = data.candidates?.[0]?.content?.parts?.map((part) => part.text || '').join('');
    if (!text) return res.status(502).json({ message: 'Support suggestions could not be generated. Please try again.' });
    const insight = JSON.parse(text);
    const activity = await StudentActivity.create({
      student: req.user._id,
      type: 'insight_generated',
      forecast: latestForecast.forecast,
      record: latestForecast.record,
      insight: { ...insight, model, promptVersion: 'student-support-v1' },
    });
    res.status(201).json({ insight, createdAt: activity.createdAt });
  } catch (err) {
    if (err.code === 'ECONNABORTED') {
      return res.status(504).json({ message: 'The server could not reach Gemini before the request timed out. Check this server\'s internet connection, proxy, or firewall rules for generativelanguage.googleapis.com.' });
    }
    if (err.response) {
      const apiMessage = err.response.data?.error?.message;
      return res.status(502).json({ message: apiMessage ? `Gemini could not generate suggestions: ${apiMessage}` : 'Gemini could not generate support suggestions. Please try again later.' });
    }
    if (err instanceof SyntaxError) return res.status(502).json({ message: 'Gemini returned an invalid support-suggestions response. Please try again.' });
    next(err);
  }
};
