import { useEffect, useState } from "react";
import { BarChart3, FilePenLine, FilePlus2, History as HistoryIcon } from "lucide-react";
import { useAuth } from "../context/AuthContext";

const eventCopy = { record_created: { label: "Academic record created", icon: FilePlus2 }, record_updated: { label: "Academic record updated", icon: FilePenLine }, forecast_run: { label: "Forecast run", icon: BarChart3 }, insight_generated: { label: "Support suggestions generated", icon: BarChart3 } };
const formatDate = (value) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export default function HistoryView({ user }) {
  const { apiFetch } = useAuth();
  const [state, setState] = useState({ loading: user?.role === "student", error: "", activities: [] });
  useEffect(() => { if (user?.role !== "student") return; let active = true; (async () => { try { const response = await apiFetch("/api/students/me/history"); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Could not load your history."); if (active) setState({ loading: false, error: "", activities: data.activities || [] }); } catch (error) { if (active) setState({ loading: false, error: error.message || "Could not load your history.", activities: [] }); } })(); return () => { active = false; }; }, [apiFetch, user?.role]);
  if (user?.role !== "student") return <section className="workspace-section" id="history"><div className="section-heading"><div><p className="dashboard-eyebrow">Forecast history</p><h2>Coming soon</h2></div></div><p className="dashboard-subtext">Student activity history is currently available to each student for their own records and forecasts.</p></section>;
  if (state.loading) return <p className="student-data-loading">Loading your history…</p>;
  return <section className="workspace-section" id="history"><div className="section-heading"><div><p className="dashboard-eyebrow">Your activity</p><h2>Record and forecast history</h2></div></div><p className="dashboard-subtext">A permanent timeline of changes to your academic record and every forecast you choose to run.</p>{state.error && <div className="login-alert" role="alert">{state.error}</div>}{!state.error && state.activities.length === 0 ? <div className="empty-state"><div className="empty-illustration"><HistoryIcon size={29} /></div><div><h3>No activity yet</h3><p>Save your academic record or run a forecast to start your timeline.</p></div></div> : <ul className="history-timeline history-timeline--live">{state.activities.map((entry) => { const details = eventCopy[entry.type]; const Icon = details.icon; const forecast = entry.forecast; return <li key={entry.id} className="history-timeline-item"><span className="history-timeline-icon"><Icon size={16} /></span><div><strong>{details.label}</strong><small>{formatDate(entry.createdAt)}</small>{entry.type !== "forecast_run" && entry.record && <small>Grade: {entry.record.previousSemesterGrade} / {entry.record.gradeMaximum} · Units approved: {entry.record.previousSemesterUnitsApproved}</small>}</div>{forecast && <span className="history-timeline-value">{forecast.predictedNextSemesterGrade} / {forecast.gradeMaximum}<small>{Math.round(forecast.dropoutProbability * 100)}% dropout probability</small></span>}</li>; })}</ul>}</section>;
}
